# Generate FSRS numerical-parity fixtures from py-fsrs (the reference implementation).
# Output: a Dart const file consumed by app/test/fsrs_pyfsrs_parity_test.dart.
#
# Provenance discipline (mirrors the project's data-pipeline rules):
# this file is generated, committed, and its values are pinned to
# py-fsrs == the version printed below. Re-run only when upgrading py-fsrs.
import sys
from datetime import datetime, timedelta, timezone

import fsrs
from fsrs import Scheduler, Card, Rating

SCHED = Scheduler(
    learning_steps=[],
    relearning_steps=[],
    enable_fuzzing=False,
    maximum_interval=36500,
)
T0 = datetime(2026, 1, 15, 8, 0, tzinfo=timezone.utc)

scenarios = {}


def run(name, steps):
    card = Card()
    rows = []
    for rating_name, dt in steps:
        card, _log = SCHED.review_card(card, Rating[rating_name], dt)
        rows.append((rating_name, card.stability, card.difficulty))
    scenarios[name] = rows


run("A", [
    ("Again", T0),
    ("Again", T0 + timedelta(minutes=10)),
    ("Easy", T0 + timedelta(minutes=20)),
])
run("B", [
    ("Easy", T0),
    ("Hard", T0 + timedelta(days=5)),
    ("Hard", T0 + timedelta(days=17)),
    ("Easy", T0 + timedelta(days=20)),
    ("Again", T0 + timedelta(days=50)),
    ("Easy", T0 + timedelta(days=50, minutes=10)),
])
run("C", [
    ("Hard", T0),
    ("Hard", T0 + timedelta(days=3)),
    ("Again", T0 + timedelta(days=11)),
    ("Again", T0 + timedelta(days=11, minutes=10)),
    ("Hard", T0 + timedelta(days=12, minutes=11)),   # +24h1min -> long-term boundary
    ("Easy", T0 + timedelta(days=12, hours=23, minutes=11)),  # +23h -> short-term boundary
])

Ds = [1.0, 5.5, 9.0]
Ss = [0.5, 5.0, 50.0]
Rs = [0.3, 0.7, 0.95]

forget = []
recall = []
for d in Ds:
    for s in Ss:
        for r in Rs:
            forget.append((d, s, r, SCHED._next_forget_stability(difficulty=d, stability=s, retrievability=r)))
            recall.append((d, s, r, SCHED._next_recall_stability(difficulty=d, stability=s, retrievability=r, rating=Rating.Hard)))
            recall.append((d, s, r, SCHED._next_recall_stability(difficulty=d, stability=s, retrievability=r, rating=Rating.Easy)))

short_term = []
for s in Ss:
    for g, name in [(1, "Again"), (2, "Hard"), (4, "Easy")]:
        short_term.append((s, g, SCHED._short_term_stability(stability=s, rating=Rating(g))))

difficulty = []
for d in Ds:
    for g in (1, 2, 4):
        difficulty.append((d, g, SCHED._next_difficulty(difficulty=d, rating=Rating(g))))

retr = []
for s in [0.5, 5.0, 50.0, 365.0]:
    for t in [0, 1, 7, 30, 365]:
        retr.append((s, t, (1 + SCHED._FACTOR * t / s) ** SCHED._DECAY))

interval = [(s, SCHED._next_interval(stability=s)) for s in [0.1, 1.0, 10.0, 100.0, 1000.0]]

initial_s = [(g, SCHED._initial_stability(rating=Rating(g))) for g in (1, 2, 4)]
initial_d = [(g, SCHED._initial_difficulty(rating=Rating(g), clamp=True)) for g in (1, 2, 4)]


def n(x):
    return repr(round(float(x), 12))


out = []
out.append("// GENERATED by tools/data/gen_fsrs_fixtures.py from py-fsrs (reference implementation).")
out.append(f"// py-fsrs version: {getattr(fsrs, '__version__', 'unknown')}; parameters: default FSRS-6,")
out.append("// desiredRetention=0.9, maximumInterval=36500, fuzzing off, learning/relearning steps empty")
out.append("// (the Dart port has no learning steps; see fsrs_scheduler.dart header).")
out.append("// Regenerate only when upgrading the reference; do not edit numbers by hand.")
out.append("")
out.append("// ignore_for_file: lines_longer_than_80_chars")
out.append("library;")
out.append("")
out.append("/// 每行：[difficulty, stability, retrievability, expectedStabilityAfterForget]")
out.append("const fsrsForgetGrid = <List<double>>[")

def fmt(row):
    return "  [" + ", ".join(n(v) for v in row) + "],"

for row in forget:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[difficulty, stability, retrievability, expectedStabilityAfterRecall]")
out.append("/// recall 交替使用 Hard(2) 与 Easy(4)，覆盖 hardPenalty 与 easyBonus 两个乘数。")
out.append("const fsrsRecallGrid = <List<double>>[")
for row in recall:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[stability, ratingValue, expectedShortTermStability]")
out.append("const fsrsShortTermGrid = <List<double>>[")
for row in short_term:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[difficulty, ratingValue, expectedNextDifficulty]")
out.append("const fsrsDifficultyGrid = <List<double>>[")
for row in difficulty:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[stability, elapsedDays, expectedRetrievability]")
out.append("const fsrsRetrievabilityGrid = <List<double>>[")
for row in retr:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[stability, expectedIntervalDays]（整数保存在 double 里）")
out.append("const fsrsIntervalGrid = <List<double>>[")
for row in interval:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[ratingValue, expectedInitialStability]")
out.append("const fsrsInitialStability = <List<double>>[")
for row in initial_s:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 每行：[ratingValue, expectedInitialDifficulty]")
out.append("const fsrsInitialDifficulty = <List<double>>[")
for row in initial_d:
    out.append(fmt(row))
out.append("];")
out.append("")
out.append("/// 场景对拍：每步 [ratingValue, stability, difficulty]。")
out.append("/// 注意 due/interval/state 不参与对拍 —— Dart 移植对「忘了 → 10 分钟后重练」")
out.append("/// 的排程是刻意的产品决定，与 py-fsrs（空学习步时给出整天间隔）不同；")
out.append("/// 对拍只锁**数学**：稳定性与难度演化。")
out.append("const fsrsScenarios = <String, List<List<double>>>{")
for name, rows in scenarios.items():
    out.append(f"  '{name}': [")
    for rating_name, st, df in rows:
        g = {"Again": 1, "Hard": 2, "Good": 3, "Easy": 4}[rating_name]
        out.append("    [" + ", ".join([str(g), n(st), n(df)]) + "],")
    out.append("  ],")
out.append("};")

path = sys.argv[1] if len(sys.argv) > 1 else "fsrs_pyfsrs_fixtures.dart"
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print(f"written {path}")
